menu:
    Blog: /
    Archive: /archives/
    Weibo: https://www.weibo.com/lattezforever
    GitHub: https://github.com/latte-z
    Rss: /atom.xml
    #About: /about

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: lattez
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2013
